apiVersion: v1
kind: Namespace

metadata:
  name: sentinel43

  labels:
    app.kubernetes.io/part-of: sentinel43

    # Enforce the Kubernetes Restricted Pod Security Standard.
    # Workloads also define explicit securityContext settings.
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
