apiVersion: v1
kind: ServiceAccount
metadata:
  name: s43-api
  namespace: sentinel43
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: s43-core
  namespace: sentinel43
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: s43-db
  namespace: sentinel43
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: s43-migration
  namespace: sentinel43
automountServiceAccountToken: false
