# =============================================================================
# Sentinel-43
#
# Copyright (c) 2026 Justin Armstrong
# All Rights Reserved.
#
# Sentinel-43 is distributed under a dual-license model:
#   1. GNU Affero General Public License (AGPL v3.0)
#   2. Commercial License
#
# core/cli/generate_secrets.py
# =============================================================================
"""
Sentinel-43 Secret Generator — canonical implementation.

Called by three surfaces:
  scripts/generate_secrets.py          direct script execution (pre-install)
  s43-generate-secrets                 installed entry point (pyproject.toml)
  docker compose --profile setup run   Docker setup service

Safety contract:
  - Never imported by the application at runtime.
  - Never rotates secrets silently.
  - Never overwrites existing .env values without --force.
  - Never prints raw secret values except to stdout on explicit request.
  - Does not start background threads, open ports, or write outside the
    target .env file.
  - Never silently leaves a derived value (DATABASE_URL) out of sync with
    the secret it's derived from (POSTGRES_PASSWORD) — see
    _warn_stale_database_url below. It still won't auto-edit DATABASE_URL
    (that would mean parsing/rewriting a connection string this tool
    doesn't own the shape of), but it will refuse to stay quiet about it.

Usage:
  python scripts/generate_secrets.py                  print to stdout
  python scripts/generate_secrets.py --write .env     append missing secrets
  python scripts/generate_secrets.py --write .env --force   rotate all
  python scripts/generate_secrets.py --check .env     validate existing .env
  python scripts/generate_secrets.py --password-hash  generate operator hash
"""

from __future__ import annotations

import argparse
import hashlib
import os
import secrets
import sys
from datetime import datetime, timezone
from getpass import getpass
from pathlib import Path
from typing import Final

# Key used to record when secrets were last (re)generated by this tool.
# Read and enforced by core/bootstrap.py in production — see
# _verify_secret_rotation_freshness there. Never hand-edit this value;
# it's meant to reflect when this script actually ran, not a claim about
# when secrets "should" be considered rotated.
_ROTATION_TIMESTAMP_KEY: Final[str] = "S43_SECRETS_ROTATED_AT"


# =============================================================================
# Bootstrap constants — imported from their canonical source modules when
# available. Fallback values match those modules so the tool stays correct
# when run before the package is installed (e.g. first-time setup from a
# fresh clone).
#
# APPROVED_JWT_ALGORITHMS lives in core.security.jwt_constants, NOT
# core.bootstrap. core/bootstrap.py imports it from there too — importing
# it from core.bootstrap here would only work as a side effect of that
# module's own import, not because core.bootstrap actually owns the value.
# Depend on the real source directly.
# =============================================================================

try:
    from core.bootstrap import _MIN_PEPPER_BYTES, _MIN_JWT_SECRET_BYTES  # type: ignore[import]
    from core.security.jwt_constants import APPROVED_JWT_ALGORITHMS  # type: ignore[import]
    _BOOTSTRAP_IMPORTED = True
except ImportError:
    APPROVED_JWT_ALGORITHMS: frozenset[str] = frozenset({"HS256"})  # type: ignore[assignment]
    _MIN_PEPPER_BYTES: int = 32                                       # type: ignore[assignment]
    _MIN_JWT_SECRET_BYTES: int = 32                                   # type: ignore[assignment]
    _BOOTSTRAP_IMPORTED = False

# Single entropy floor for this tool, derived from whichever bootstrap
# constant is stricter. Both are 32 today; if one changes, this stays
# correct without a second hardcoded literal to forget about.
_MIN_ENTROPY_BYTES: Final[int] = max(_MIN_PEPPER_BYTES, _MIN_JWT_SECRET_BYTES)


# =============================================================================
# Secret registry
#
# Each entry is (env_key, generator_fn, section_comment).
# Section comments produce grouped output in render_env_block().
#
# Keys excluded from this registry (managed separately):
#   S43_OPERATOR_PASSWORD_HASH  — derived from user password, use --password-hash
#   DATABASE_URL                — derived from POSTGRES_PASSWORD, not random.
#                                 NOT auto-edited by this tool, but checked
#                                 for staleness after a POSTGRES_PASSWORD
#                                 rotation — see _warn_stale_database_url.
#   S43_JORM_ROOT_KEY           — only needed when S43_JORM_ENABLED=true
#   S43_SPARTA_TOKEN_SECRET     — only needed when S43_SPARTA_ENABLED=true
#   S43_SPARTA_NODE_TOKEN       — only needed when S43_SPARTA_ENABLED=true
# =============================================================================

# Generator callables: each takes num_bytes (int) and returns a str.
# token_hex    — for salts, peppers, DB passwords (avoids URL-special chars)
# token_urlsafe — for bearer tokens and JWT secrets (shorter, header-safe)
def _hex(n: int) -> str:
    return secrets.token_hex(n)

def _url(n: int) -> str:
    return secrets.token_urlsafe(n)


_REGISTRY: tuple[tuple[str, object, str | None], ...] = (
    # (env_key, generator_fn, section_heading or None)
    ("S43_JWT_SECRET",               _url,  "JWT signing"),
    ("S43_AUTH_PEPPER",              _hex,  "Auth key-store hardening (required in production by bootstrap.py)"),
    ("SENTINEL_LOG_SALT",            _hex,  "Log pseudonymization salt (hashing of IPs/identities in logs)"),
    ("SENTINEL_REMOTE_TOKEN_OWNER",  _url,  "Remote gateway operator tokens"),
    ("SENTINEL_REMOTE_TOKEN_ADMIN",  _url,  None),
    ("SENTINEL_REMOTE_TOKEN_AUDITOR",_url,  None),
    ("S43_FENRIR_API_TOKEN",         _url,  "Fenrir internal API token (required when S43_FENRIR_ENABLED=true)"),
    ("S43_WATCHTOWER_SERVICE_TOKEN", _url,  "Watchtower internal-service token (required — shared by s43-api and s43-core; Watchtower fails closed without it)"),
    ("POSTGRES_PASSWORD",            _hex,  "Infrastructure"),
    ("REDIS_PASSWORD",               _hex,  None),
)

SECRET_KEYS: Final[tuple[str, ...]] = tuple(key for key, _, _ in _REGISTRY)

# Values that indicate a secret has never been set.
_PLACEHOLDERS: Final[frozenset[str]] = frozenset({
    "", "CHANGE_ME", "CHANGE_ME_IN_PROD", "CHANGEME",
    "dev-placeholder", "development", "password", "secret",
    "your-secret-here", "replace-me",
})

DEFAULT_BYTES: Final[int] = _MIN_ENTROPY_BYTES


# =============================================================================
# Generators
# =============================================================================

def generate_env_values(*, num_bytes: int = DEFAULT_BYTES) -> dict[str, str]:
    """Generate a fresh value for every key in SECRET_KEYS."""
    if num_bytes < _MIN_ENTROPY_BYTES:
        raise ValueError(f"num_bytes must be >= {_MIN_ENTROPY_BYTES}")
    return {key: gen(num_bytes) for key, gen, _ in _REGISTRY}


# =============================================================================
# .env file helpers
# =============================================================================

def parse_env_file(path: Path) -> dict[str, str]:
    """
    Parse KEY=VALUE pairs from a .env file.

    Skips comments and blank lines. Does not expand shell variables.
    Returns an empty dict if the file does not exist.
    """
    if not path.exists():
        return {}

    result: dict[str, str] = {}
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        result[key.strip()] = value.strip()
    return result


def render_env_block(values: dict[str, str]) -> str:
    """
    Render generated values as a structured, copy-pasteable .env block.
    Sections are grouped with comments matching the registry headings.
    """
    lines: list[str] = [
        "# =============================================================================",
        "# Sentinel-43 generated secrets",
        "# Generated once. Store securely. Do not commit .env to version control.",
        "# Rotate intentionally with: python scripts/generate_secrets.py --write .env --force",
        "# =============================================================================",
        "",
    ]

    last_section: str | None = object()  # sentinel — different from None and any string

    for key, _, section in _REGISTRY:
        if section is not None and section != last_section:
            if lines and lines[-1] != "":
                lines.append("")
            lines.append(f"# {section}")
            last_section = section
        lines.append(f"{key}={values[key]}")

    lines += [
        "",
        "# --- Set these manually (not randomly generated) ---",
        "# S43_OPERATOR_PASSWORD_HASH=<run: python scripts/generate_secrets.py --password-hash>",
        "# DATABASE_URL=postgresql+asyncpg://s43:<POSTGRES_PASSWORD>@s43-db:5432/s43",
        "",
    ]

    # LF line endings — avoids \r\n issues inside Docker containers on Windows.
    return "\n".join(lines)


def write_env_file(
    path: Path,
    values: dict[str, str],
    *,
    force: bool = False,
) -> list[str]:
    """
    Write generated secrets to a .env file.

    Default (force=False):
      - Keys already present: left unchanged.
      - Keys missing: appended at the end.

    With force=True:
      - Keys in SECRET_KEYS that already exist: replaced in-place.
      - All other lines, comments, and ordering: preserved.
      - Keys still missing after scan: appended.

    Returns the list of keys that were actually written or updated.

    Writes LF line endings (newline="\\n") regardless of OS to ensure
    Docker containers read the file correctly on Windows hosts.

    NOTE: this function intentionally never touches DATABASE_URL, even
    though it embeds the same password as POSTGRES_PASSWORD. See
    _warn_stale_database_url, called from main() after this function
    returns, which detects and loudly reports the resulting staleness
    instead of silently leaving it or silently rewriting a connection
    string this function doesn't parse.
    """
    if not path.exists():
        path.write_text(render_env_block(values), encoding="utf-8", newline="\n")
        return list(SECRET_KEYS)

    original = path.read_text(encoding="utf-8").splitlines()
    output: list[str] = []
    written: list[str] = []
    seen: set[str] = set()

    for raw in original:
        stripped = raw.strip()

        if "=" not in stripped or stripped.startswith("#"):
            output.append(raw)
            continue

        key, _ = stripped.split("=", 1)
        key = key.strip()

        if key in values:
            seen.add(key)
            if force:
                output.append(f"{key}={values[key]}")
                written.append(key)
            else:
                output.append(raw)
        else:
            output.append(raw)

    missing = [k for k in SECRET_KEYS if k not in seen]
    if missing:
        if output and output[-1].strip():
            output.append("")
        output.append("# Sentinel-43 generated secrets")
        for key in missing:
            output.append(f"{key}={values[key]}")
            written.append(key)

    path.write_text(
        "\n".join(output).rstrip() + "\n",
        encoding="utf-8",
        newline="\n",
    )
    return written


def _update_rotation_timestamp(path: Path) -> str:
    """
    Stamp S43_SECRETS_ROTATED_AT with the current UTC time.

    Called whenever write_env_file() actually wrote or rotated at least one
    key — including first-time creation of a fresh .env, where every key
    counts as "written". Always overwrites any existing timestamp
    unconditionally (not gated by --force): if generation happened at all,
    the timestamp must reflect that, regardless of which specific keys were
    touched.

    This is the value core/bootstrap.py's _verify_secret_rotation_freshness
    checks in production. Written as an ISO 8601 string with explicit UTC
    offset (not a bare 'Z' suffix) so it round-trips through
    datetime.fromisoformat() across Python 3.9+ without special-casing.

    Returns the timestamp string that was written, for logging.
    """
    timestamp = datetime.now(timezone.utc).isoformat()
    line = f"{_ROTATION_TIMESTAMP_KEY}={timestamp}"

    if not path.exists():
        # Shouldn't normally happen (write_env_file creates the file first),
        # but handle it defensively rather than assuming.
        path.write_text(line + "\n", encoding="utf-8", newline="\n")
        return timestamp

    original = path.read_text(encoding="utf-8").splitlines()
    output: list[str] = []
    found = False

    for raw in original:
        stripped = raw.strip()
        if stripped.startswith(f"{_ROTATION_TIMESTAMP_KEY}="):
            output.append(line)
            found = True
        else:
            output.append(raw)

    if not found:
        if output and output[-1].strip():
            output.append("")
        output.append("# Secret rotation tracking — read by core/bootstrap.py in production")
        output.append(line)

    path.write_text(
        "\n".join(output).rstrip() + "\n",
        encoding="utf-8",
        newline="\n",
    )
    return timestamp


def _warn_stale_database_url(path: Path, values: dict[str, str], written: list[str]) -> None:
    """
    POSTGRES_PASSWORD and DATABASE_URL both encode the same password as two
    independent lines in .env. This tool deliberately never auto-edits
    DATABASE_URL — see the module docstring and write_env_file's note above
    — because rewriting a connection string this tool doesn't own the exact
    shape of (custom host, port, SSL params, etc.) is riskier than just
    telling the operator to fix it.

    But staying silent about the resulting mismatch is worse: if
    POSTGRES_PASSWORD was just rotated, check whether the existing
    DATABASE_URL line still contains the new password, and if not, surface
    it loudly with the exact line to paste, rather than leaving a stale,
    easy-to-miss credential mismatch that only shows up as a connection
    failure after restart.
    """
    if "POSTGRES_PASSWORD" not in written:
        return

    existing = parse_env_file(path)
    database_url = existing.get("DATABASE_URL", "")
    new_password = values["POSTGRES_PASSWORD"]

    if database_url and new_password not in database_url:
        print(
            "\n"
            "WARNING: POSTGRES_PASSWORD was rotated but the existing "
            "DATABASE_URL line does not contain the new password.\n"
            "DATABASE_URL is intentionally never auto-edited by this tool "
            "(see module docstring) — update it manually to:\n"
            f"  DATABASE_URL=postgresql+asyncpg://s43:{new_password}@s43-db:5432/s43\n"
            "Also update the actual Postgres role password to match, or the\n"
            "new value above won't authenticate against the live database:\n"
            "  ALTER ROLE s43 WITH PASSWORD '<new POSTGRES_PASSWORD>';\n"
            "Do this before restarting the app.",
            file=sys.stderr,
        )


def check_env_file(path: Path) -> tuple[list[str], list[str], list[str]]:
    """
    Validate an existing .env file against SECRET_KEYS.

    Returns (present, missing, placeholder) lists of key names.
    A key is 'placeholder' if it exists but its value is in _PLACEHOLDERS.
    Exit code convention: 0 if missing+placeholder is empty, else 1.
    """
    existing = parse_env_file(path)
    present:     list[str] = []
    missing:     list[str] = []
    placeholder: list[str] = []

    for key in SECRET_KEYS:
        value = existing.get(key, "")
        if value in _PLACEHOLDERS:
            if key in existing:
                placeholder.append(key)
            else:
                missing.append(key)
        else:
            present.append(key)

    return present, missing, placeholder


# =============================================================================
# Algorithm / bootstrap cross-checks
# =============================================================================

def _warn_if_bootstrap_mismatch() -> None:
    """
    Warn if the runtime bootstrap constants differ from the generator's
    hardcoded fallbacks. Indicates bootstrap.py was not importable.
    """
    if not _BOOTSTRAP_IMPORTED:
        print(
            "Warning: core.bootstrap / core.security.jwt_constants could not "
            "be imported. Using hardcoded fallback constants. "
            "Run from the repo root or install the package for full validation.",
            file=sys.stderr,
        )


def _validate_jwt_algorithm(algorithm: str) -> None:
    """
    Warn if S43_JWT_ALGORITHM is not in the approved set.
    This is advisory — the generator does not refuse to run.

    Callers should pass the algorithm value from whichever .env file is
    actually the target of the current operation (--write or --check), not
    the ambient shell environment. In the primary use case for this tool —
    first-time setup from a fresh clone — the shell almost never has
    S43_JWT_ALGORITHM set, so checking os.environ alone made this check
    effectively dead code. Fall back to the ambient environment only when
    there's no target file to read from (default stdout-print mode).
    """
    if algorithm and algorithm not in APPROVED_JWT_ALGORITHMS:
        print(
            f"Warning: S43_JWT_ALGORITHM={algorithm!r} is not in the approved "
            f"algorithm set {sorted(APPROVED_JWT_ALGORITHMS)}. "
            "Update S43_JWT_ALGORITHM in .env before deployment.",
            file=sys.stderr,
        )


# =============================================================================
# Password hash flow
# =============================================================================

def password_hash_flow() -> int:
    """
    Interactively generate S43_OPERATOR_PASSWORD_HASH.

    Sentinel-43 uses sha256(password).hexdigest() for closed beta.
    Upgrade to Argon2/bcrypt before public release.
    The hash is printed to stdout only — never logged or written to disk
    by this function. Paste the output into .env manually.
    """
    print(
        "Generating S43_OPERATOR_PASSWORD_HASH\n"
        "Note: SHA-256 is used for closed beta. Upgrade to Argon2/bcrypt "
        "before public release.",
        file=sys.stderr,
    )

    try:
        password_1 = getpass("Operator password: ")
        password_2 = getpass("Confirm password:  ")
    except (KeyboardInterrupt, EOFError):
        print("\nCancelled.", file=sys.stderr)
        return 130

    if not password_1:
        print("ERROR: password cannot be empty.", file=sys.stderr)
        return 2

    if password_1 != password_2:
        print("ERROR: passwords do not match.", file=sys.stderr)
        return 2

    digest = hashlib.sha256(password_1.encode("utf-8")).hexdigest()
    print(f"S43_OPERATOR_PASSWORD_HASH={digest}")
    print(
        "\nPaste the line above into .env. "
        "Do not commit .env to version control.",
        file=sys.stderr,
    )
    return 0


# =============================================================================
# CLI
# =============================================================================

def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="generate_secrets",
        description="Generate Sentinel-43 deployment secrets safely.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  Print all generated secrets to stdout (safe to review before writing):
    python scripts/generate_secrets.py

  Write missing secrets into .env without touching existing values:
    python scripts/generate_secrets.py --write .env

  Rotate all generated secrets in .env (use intentionally):
    python scripts/generate_secrets.py --write .env --force

  Validate an existing .env for missing or placeholder secrets:
    python scripts/generate_secrets.py --check .env

  Generate the operator password hash interactively:
    python scripts/generate_secrets.py --password-hash

  Docker setup service (see docker-compose.setup.yml):
    docker compose --profile setup run --rm s43-setup --write /app/.env
""",
    )

    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        "--write",
        metavar="ENV_FILE",
        help="Write missing generated secrets to ENV_FILE. Safe by default — "
             "existing values are never overwritten without --force.",
    )
    mode.add_argument(
        "--check",
        metavar="ENV_FILE",
        help="Validate ENV_FILE for missing or placeholder secrets. "
             "Exits 0 if all present, 1 if any missing or placeholder.",
    )
    mode.add_argument(
        "--password-hash",
        action="store_true",
        help="Prompt for an operator password and print S43_OPERATOR_PASSWORD_HASH.",
    )

    parser.add_argument(
        "--force",
        action="store_true",
        help="With --write: replace existing generated keys with fresh values. "
             "Use intentionally during planned secret rotation.",
    )
    parser.add_argument(
        "--bytes",
        type=int,
        default=DEFAULT_BYTES,
        metavar="N",
        help=f"Entropy bytes per secret (default: {DEFAULT_BYTES}, minimum: {_MIN_ENTROPY_BYTES}).",
    )

    return parser


def _ensure_utf8_stdio() -> None:
    """
    --check prints unicode markers (checkmark/cross/bang). Windows consoles
    default stdout/stderr to the system codepage (cp1252 etc.), which raises
    UnicodeEncodeError on those characters — this tool would crash on plain
    `python core/cli/generate_secrets.py --check .env` in an ordinary
    Windows terminal, not just in some unusual environment. Reconfigure to
    UTF-8 with a replace fallback so it never crashes on encoding alone,
    regardless of the host console's default codepage.
    """
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")
        except (AttributeError, ValueError):
            pass


def main(argv: list[str] | None = None) -> int:
    _ensure_utf8_stdio()

    parser = _build_parser()
    args = parser.parse_args(argv)

    _warn_if_bootstrap_mismatch()

    # --- --password-hash ---
    if args.password_hash:
        return password_hash_flow()

    # --- --check ---
    if args.check:
        env_path = Path(args.check)
        if not env_path.exists():
            print(f"ERROR: {env_path} does not exist.", file=sys.stderr)
            return 1

        _validate_jwt_algorithm(parse_env_file(env_path).get("S43_JWT_ALGORITHM", ""))

        present, missing, placeholder = check_env_file(env_path)
        width = max(len(k) for k in SECRET_KEYS)

        print(f"Checking {env_path} ({len(SECRET_KEYS)} required secrets):\n")
        for key in SECRET_KEYS:
            if key in present:
                marker = "✓"
                status = "present"
            elif key in placeholder:
                marker = "!"
                status = "PLACEHOLDER — replace before deployment"
            else:
                marker = "✗"
                status = "MISSING"
            print(f"  {marker}  {key:<{width}}  {status}")

        problems = len(missing) + len(placeholder)
        print()
        if problems == 0:
            print(f"All {len(SECRET_KEYS)} secrets present. ✓")
            return 0
        else:
            print(
                f"{problems} problem(s) found. "
                f"Run: python scripts/generate_secrets.py --write {env_path}"
            )
            return 1

    # --- entropy validation ---
    if args.bytes < _MIN_ENTROPY_BYTES:
        print(f"ERROR: --bytes must be >= {_MIN_ENTROPY_BYTES}.", file=sys.stderr)
        return 2

    values = generate_env_values(num_bytes=args.bytes)

    # --- --write ---
    if args.write:
        env_path = Path(args.write)

        _validate_jwt_algorithm(
            parse_env_file(env_path).get("S43_JWT_ALGORITHM", os.getenv("S43_JWT_ALGORITHM", ""))
        )

        written = write_env_file(env_path, values, force=args.force)
        _warn_stale_database_url(env_path, values, written)

        if written:
            timestamp = _update_rotation_timestamp(env_path)
            action = "Rotated" if args.force else "Wrote"
            print(f"{action} {len(written)} key(s) to {env_path}:")
            for key in written:
                print(f"  + {key}")
            print(f"\n{_ROTATION_TIMESTAMP_KEY}={timestamp}")
            print(
                f"\nNext step: set S43_OPERATOR_PASSWORD_HASH with --password-hash\n"
                f"Then rebuild: docker compose build --no-cache s43-api"
            )
        else:
            print(
                f"No changes made to {env_path}.\n"
                "All generated keys already exist. "
                "Use --force to rotate intentionally."
            )
        return 0

    # --- default: print to stdout ---
    _validate_jwt_algorithm(os.getenv("S43_JWT_ALGORITHM", ""))
    print(render_env_block(values), end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
