"""Conservative secret-provisioning entrypoint; never rotates existing values."""
from __future__ import annotations
import argparse
from pathlib import Path

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--env-file", default=".env")
    args = parser.parse_args()
    env = Path(args.env_file)
    if env.is_symlink():
        parser.error("Refusing a symlink environment file")
    if env.exists():
        print("Existing environment file preserved; use the reviewed Compose bootstrap for validation.")
        return 0
    print("Environment file missing. Use the reviewed Compose bootstrap after PR #442 is merged; no secrets generated by this helper.")
    return 2

if __name__ == "__main__":
    raise SystemExit(main())
